/*
 * Copyright (c) 2026 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */

#define SPLIT_ROLE_CENTRAL_CMD 0
#define SPLIT_ROLE_PERIPHERAL_CMD 1
#define SPLIT_ROLE_TOGGLE_CMD 2

#define SPLIT_ROLE_CENTRAL SPLIT_ROLE_CENTRAL_CMD
#define SPLIT_ROLE_PERIPHERAL SPLIT_ROLE_PERIPHERAL_CMD
#define SPLIT_ROLE_TOGGLE SPLIT_ROLE_TOGGLE_CMD
